- hosts: testing
  become: yes
  vars: 
      ansible_config_file: /home/semaphore/ansible/ansible.cfg
  tasks:
    - name: restart apache2
      ansible.builtin.systemd:
        name: apache2
        state: restarted
