- hosts: proxmox
  become: yes
  tasks:
    - import_tasks: ../deployment/deploy.yml
    - import_tasks: deployment/k8sconfig.yml

    - name: register new node
      ansible.builtin.add_host:
        name: "{{ ipadr }}"
        group: new_host

    - name: wait for the machine to fully boot
      ansible.builtin.pause:
        seconds: 30

- hosts: new_host
  become: yes
  tasks:
    - import_tasks: deployment/netconfig.yml
