- hosts: proxmox
  become: yes
  tasks:
    - import_tasks: ../deployment/deploy.yml
    - import_tasks: deployment/k8sconfig.yml

    - name: register new node
      ansible.builtin.add_host:
        name: "{{ ipadr }} ansible_ssh_user=root"
        group: new_host

- hosts: new_host
  become: yes
  tasks:
    - import_tasks: deployment/netconfig.yml
