- hosts: proxmox
  become: yes
  tasks:
    - import_tasks: ../deployment/deploy.yml
    - import_tasks: deployment/k8sconfig.yml

    - name: register new node
      ansible.builtin.add_host:
        name: "{{ ipadr }}"
        group: new_host

- hosts: 10.0.50.10 
  become: yes
  tasks:
    - name: wait for the machine to fully boot
      wait_for:
        host: "{{ ipadr }}"
        port: 22
        delay: 10

- hosts: new_host
  become: yes
  tasks:
    - import_tasks: deployment/netconfig.yml
