- hosts: proxmox
  become: yes 
  tasks:
    - import_tasks: ../deployment/deploy.yml
    - import_tasks: deployment/k8sconfig.yml

    - name: register new node
      ansible.builtin.add_host:
        name: "{{ ipadr }}"
        ansible_user: root
        group: new_host

    - name: wait for the machine to fully boot
      ansible.builtin.pause:
        seconds: 15

- hosts: new_host
  become: true 
  gather_fatcs: no
  vars:
    ansible_ssh_user: "root"
      #    allow_world_readable_tmpfiles: true

  tasks:
#    - import_tasks: deployment/netconfig.yml
    - import_tasks: ../playbooks/shutdown.yml
