  - name: adjust disk size 
    shell: qm resize {{ vmid }} scsi0 +{{ disksize }}G

  - name: set IP address
    shell: qm set {{ vmid }} --ipconfig0 ip={{ ipadr }},gw={{ gateway }}
  
  - name: set vlan tag
    shell: qm set {{ vmid }} -net0 virtio,bridge=vmbr0,tag={{ vlanTag }}

  - name: set memory
    shell: qm set {{ vmid }} --memory {{ mem }}

  - name: set cpu cores
    shell: qm set {{ vmid }} --cores {{ cpu  }}

  - name: start VM
    shell: qm start {{ vmid }}

  - name: wait 5 seconds
    ansible.builtin.pause:
      seconds: 5 
 
  - name: reset vm because kernel panic at first boot for some reason
    shell: qm reset {{ vmid }}

  - name: wait 10 seconds
    ansible.builtin.pause:
      seconds: 10 
