# - name: add zabbix repository to host
#   ansible.builtin.apt_repository:
#     repo: deb https://repo.zabbix.com/zabbix/6.2/debian bullseye main 
#     state: present


- name: download the zabbix repository
  ansible.builtin.get_url:
    url: https://repo.zabbix.com/zabbix/6.2/debian/pool/main/z/zabbix-release/zabbix-release_6.2-4%2Bdebian9_all.deb
    dest: /tmp/zabbix-repo.deb
