# - name: add zabbix repository to host
#   ansible.builtin.apt_repository:
#     repo: deb https://repo.zabbix.com/zabbix/6.2/debian bullseye main 
#     state: present


- name: download the zabbix repository
  ansible.builtin.get_url:
    url: https://repo.zabbix.com/zabbix/6.2/debian/pool/main/z/zabbix-release/zabbix-release_6.2-4%2Bdebian11_all.deb
    dest: /tmp/zabbix-repo.deb

- name: install zabbix repositoy
  ansible.builtin.apt:
    deb: /tmp/zabbix-repo.deb

- name: run apt update
  ansible.builtin.apt:
    update_cache: yes

- name: install zabbix agent 2
  ansible.builtin.apt: 
    pkg:
      - zabbix-agent2

- name: current date
  debug:
    msg: "{{ ansible_date_time.data }}"
