 - name: ensure k8s.conf is configured correctly
   ansible.builtin.shell: echo -e "overlay\nbr_netfilter" > /etc/modules-load.d/k8s.conf

 - name: set k8s.conf in sysctl.d
   ansible.builtin.shell: echo -e "net.bridge.bridge-nf-call-iptables  = 1\nnet.bridge.bridge-nf-call-ip6tables = 1\net.ipv4.ip_forward                  = 1" > /etc/sysctl.d/k8s.conf

 - name: enable ip forwarding
   ansible.posix.sysctl:
   name: net.ipv4.ip_forward
   value: '1'
   sysctl_set: true
   state: present
   reload: true

 - name: reload systemd
   ansible.builtin.shell: sysctl -system


