 - name: ensure k8s.conf is configured correctly
   ansible.builtin.shell: echo -e "overlay\nbr_netfilter" > /etc/modules-load.d/k8s.conf

     # - name: set k8s.conf in sysctl.d
     #ansible.builtin.shell: echo -e "net.bridge.bridge-nf-call-iptables  = 1\nnet.bridge.bridge-nf-call-ip6tables = 1\net.ipv4.ip_forward                  = 1" > /etc/sysctl.d/k8s.conf
 - name: make sure /etc/sysctl.d/k8s.conf exists
   ansible.builtin.file:
     path: /etc/sysctl.d/k8s.conf
     state: touch 

 - name: set netbridge-nf-call-iptables
   ansible.posix.sysctl:
     name: net.bridge.bridge-nf-call-iptables
     value: '1'
     sysctl_file: /etc/sysctl.d/k8s.conf
     sysctl_set: true
     state: present
     reload: true

 - name: set netbridge-nf-call-ip6tables
   ansible.posix.sysctl:
     name: net.bridge.bridge-nf-call-ip6tabels
     value: '1'
     sysctl_file: /etc/sysctl.d/k8s.conf
     sysctl_set: true
     state: present
     reload: true

 - name: enable ip forwarding
   ansible.posix.sysctl:
     name: net.ipv4.ip_forward
     value: '1'
     sysctl_set: true
     state: present
     reload: true

 - name: reload systemd
   ansible.builtin.shell: sysctl -system


