 - name: install deps
   apt: pkg={{ item }}
   with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - lsb-release
     - gnupg

 - name: make keyring directory
   ansible.builtin.file:
     path: /etc/apt/keyrings
     state: directory
     mode: '0755'

 - name: install docker gpg key
   ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

 - name: install docker repository
   ansible.builtin.shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
 
  # doing it the dirty way because ansible.builtin.apt has a habit of failing
 - name: apt update
   ansible.builtin.shell: apt update

     #- name: apt update
     #ansible.builtin.apt:
     #update_cache: yes
     #name: containerd
     #state: present
 
 - name: install deps
   apt: pkg={{ item }}
   with_items:
     - containerd.io

 - name: create directory for plugin
   ansible.builtin.file:
     path: /opt/cni/bin
     state: directory
     mode: '0755'

 - name: download plugins
   ansible.builtin.get_url:
     url: https://github.com/containernetworking/plugins/releases/download/v1.2.0/cni-plugins-linux-amd64-v1.2.0.tgz
     dest: /opt/cni/bin/cni-plugins.tgz

 - name: extract archive 
   ansible.builtin.unarchive:
     src: /opt/cni/bin/cni-plugins.tgz
     dest: /opt/cni/bin/
     remote_src: yes

       # - name: clear the line in the config file 
       #ansible.builtin.shell: sed -i -e '9d' /etc/containerd/config.toml

 - name: make containerd use the cgroup driver
   ansible.builtin.shell: echo "    SystemdCgroup = true" >> /etc/containerd/config.toml

 - name: enable and start containerd
   ansible.builtin.systemd:
     enabled: true
     state: started
     name: containerd
