 - name: create nic for the vm
   community.general.proxmox_nic:
     api_user: "root@pam"
     api_password: "{{ password }}"
     api_host: "artoria"
     vmid: "{{ vmid }}"
     interface: net1
     bridge: vmbr0
     tag: "{{ kubeVlan }}"

 - name: change the second network adapter 
   community.general.proxmox_kvm:
      node: "artoria"
      api_user: "root@pam"
      api_password: "{{ password }}"
      api_host: "artoria"
      vmid: "{{ vmid }}" 
      ipconfig: 
        ipconfig1: "ip={{ kubeIp }}/24"
      update: true 


