- hosts: all
  become: yes
  tasks:
    - name: check clamav presence
      shell: "if systemctl | grep clamav-freshclam.service; then echo true; else echo false; fi;"
      register: service_exists

    - name: test
      ansible.builtin.shell: init 0
      when: service_exists = true

