- hosts: all
  become: yes
  tasks:
    - name: populate service facts
      ansible.builtin.service_facts:
    - name: check clamav presence
      ansible.builtin.debug: 
        msg: clamav is installed
      when: "'clamav-freshclam.services' is in services"

