- hosts: local
  become: yes
  tasks:
    #- name: clear host file
    #ansible.builtin.shell: sed -i -e '5d' /home/semaphore/dynamic.host  
        #- name: update host file
        # ansible.builtin.shell: sed -i '5i {{ targetIP }} ansible_ssh_user=root' /home/semaphore/dynamic.host

    - name: testing again 
      ansible.builtin.add_host:
        name: "{{ targetIP }}"
          #ansible_host: "{{ targetIP }} ansible_ssh_user=root"
        group: new_host

- hosts: new_host 
  tasks:
    - import_tasks: shutdown.yml 

